version: "3.7"

services:
  ui:
    build:
      context: .
      dockerfile: "Dockerfile"
    environment:
      PORT: "9090"
      NODE_ENV: "production"
      API_URL: "https://survey-panda-api.herokuapp.com/"
    ports:
      - "9090:9090"
