version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t "$CIRCLE_PROJECT_REPONAME_$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM" .
  test:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - ~/repo/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test
